/**
 * Bundles only the Solar icons the app uses, so icons render offline and instantly
 * (no requests to the Iconify API, no multi-MB icon set in the bundle).
 *
 * Scans `src/` for `solar:<name>` strings and writes `src/libs/utils/icons.ts`.
 * Runs automatically before `npm run dev` / `npm run build` (see package.json).
 */
import { readdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { join, relative } from "node:path";
import { fileURLToPath } from "node:url";
import { getIcons } from "@iconify/utils";

const root = fileURLToPath(new URL("..", import.meta.url));
const srcDir = join(root, "src");
const outFile = join(srcDir, "libs", "utils", "icons.ts");
const solar = JSON.parse(readFileSync(join(root, "node_modules", "@iconify-json", "solar", "icons.json"), "utf8"));

function walk(dir) {
  return readdirSync(dir).flatMap((name) => {
    const path = join(dir, name);
    return statSync(path).isDirectory() ? walk(path) : [path];
  });
}

const used = new Set();

for (const file of walk(srcDir)) {
  if (!/\.(tsx?|jsx?)$/.test(file) || file === outFile) {
    continue;
  }

  for (const match of readFileSync(file, "utf8").matchAll(/solar:([a-z0-9]+(?:-[a-z0-9]+)*)/g)) {
    used.add(match[1]);
  }
}

const names = [...used].sort();
const subset = getIcons(solar, names);
const missing = names.filter((name) => !subset?.icons[name] && !subset?.aliases?.[name]);

if (missing.length) {
  console.error(`[icons] Unknown Solar icon(s): ${missing.join(", ")}`);
  console.error("[icons] Browse valid names at https://icon-sets.iconify.design/solar/");
  process.exit(1);
}

const output = `// AUTO-GENERATED by scripts/generate-icons.mjs — do not edit.
// Offline subset of the Solar icon set (${names.length} icons) used by <Icon icon="solar:..." />.
import { addCollection } from "@iconify/react";

addCollection(${JSON.stringify(subset)});
`;

writeFileSync(outFile, output);
console.log(`[icons] Bundled ${names.length} Solar icons → ${relative(root, outFile)}`);
